services:
  oracle:
    image: palantirtechnologies/oracle-atlasdb:19.25
    volumes:
      - ./docker-startup:/opt/oracle/scripts/startup      
    ports:
      - "1521:1521"
    environment:
      ORACLE_SYS_PASSWORD: 7_SeeingStones_7
      MEMORY: 8Gi
