version: '2'

services:
  cassandra1:
    image: palantirtechnologies/cassandra:2.2.18-1.143.0-rc6
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7191:7191"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7191
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra1,cassandra2,cassandra3
    container_name: cassandra1
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.2

  cassandra2:
    image: palantirtechnologies/cassandra:2.2.18-1.143.0-rc6
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7192:7192"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7192
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra1,cassandra2,cassandra3
    container_name: cassandra2
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.3

  cassandra3:
    image: palantirtechnologies/cassandra:2.2.18-1.143.0-rc6
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7193:7193"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7193
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra1,cassandra2,cassandra3
    container_name: cassandra3
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.4

  timelock1.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution:unspecified
    environment:
      HOSTNAME: timelock1.palantir.pt:8421
    command: [ bash, -c, 'sed "s/{{HOSTNAME}}/$${HOSTNAME}/g" var/conf/timelock.distributed.yml > var/conf/timelock.yml
                          && service/bin/init.sh console' ]
    ports:
      - "8421"
      - "8422"
    container_name: timelock1.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.5

  timelock2.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution:unspecified
    environment:
      HOSTNAME: timelock2.palantir.pt:8421
    command: [ bash, -c, 'sed "s/{{HOSTNAME}}/$${HOSTNAME}/g" var/conf/timelock.distributed.yml > var/conf/timelock.yml
                          && service/bin/init.sh console' ]
    ports:
      - "8421"
      - "8422"
    container_name: timelock2.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.6

  timelock3.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution:unspecified
    environment:
      HOSTNAME: timelock3.palantir.pt:8421
    command: [ bash, -c, 'sed "s/{{HOSTNAME}}/$${HOSTNAME}/g" var/conf/timelock.distributed.yml > var/conf/timelock.yml
                          && service/bin/init.sh console' ]
    ports:
      - "8421"
      - "8422"
    container_name: timelock3.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.7


  workload-server:
    image: palantirtechnologies/atlasdb-workload-server-distribution:unspecified
    command: [bash, -c, 'cp var/conf/workload-server.timelock.cassandra.yml var/conf/workload-server.yml
                         && dockerize -timeout 120s -wait tcp://cassandra1:9160 -wait tcp://cassandra2:9160 -wait tcp://cassandra3:9160
                         && service/bin/init.sh console']
    ports:
      - "5005:5005" # enabling port for remote debugger
    container_name: workload-server
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
      - timelock1.palantir.pt
      - timelock2.palantir.pt
      - timelock3.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.8

networks:
  antithesis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24
