version: '2'

services:
  cassandra11:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc4
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7191:7191"
    environment:
      - CASSANDRA_SEEDS=cassandra12,cassandra13,cassandra21,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7191
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra11
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.11

  cassandra12:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc4
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7192:7192"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra13,cassandra21,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7192
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra12
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.12

  cassandra13:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc4
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7193:7193"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra21,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7193
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra13
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.13

  cassandra14:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc4
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7194:7194"
    environment:
      - CASSANDRA_SEEDS=cassandra12,cassandra13,cassandra21,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7194
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra14
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.14

  cassandra15:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc4
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7195:7195"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra13,cassandra21,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7195
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra15
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.15

  cassandra16:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc4
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7196:7196"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra21,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7196
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra16
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.16

  cassandra21:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc5
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7291:7291"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra13,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7291
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra21
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.21

  cassandra22:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc5
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7292:7292"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra13,cassandra21,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7292
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra22
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.22

  cassandra23:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc5
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7293:7293"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra13,cassandra21,cassandra22
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7293
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra23
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.23

  cassandra24:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc5
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7294:7294"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra13,cassandra22,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7294
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra24
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.24

  cassandra25:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc5
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7295:7295"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra13,cassandra21,cassandra23
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7295
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra25
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.25

  cassandra26:
    image: palantirtechnologies/cassandra:2.2.18-1.144.0-rc5
    ports:
      - "9160"
      - "9042"
      - "7000"
      - "7001"
      - "7296:7296"
    environment:
      - CASSANDRA_SEEDS=cassandra11,cassandra12,cassandra13,cassandra21,cassandra22
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - JMX_PORT=7296
      - CASSANDRA_HINTED_HANDOFF_ENABLED=false
      - MIGRATION_MODE=true
      - ALL_HOSTS=cassandra11,cassandra12,cassandra13,cassandra14,cassandra15,cassandra16,cassandra21,cassandra22,cassandra23,cassandra24,cassandra25,cassandra26
    container_name: cassandra26
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.26

  timelock1.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution:unspecified
    environment:
      HOSTNAME: timelock1.palantir.pt:8421
    command: [ bash, -c, 'sed "s/{{HOSTNAME}}/$${HOSTNAME}/g" var/conf/timelock.distributed.yml > var/conf/timelock.yml
                          && service/bin/init.sh console' ]
    ports:
      - "8421"
      - "8422"
    container_name: timelock1.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.5

  timelock2.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution:unspecified
    environment:
      HOSTNAME: timelock2.palantir.pt:8421
    command: [ bash, -c, 'sed "s/{{HOSTNAME}}/$${HOSTNAME}/g" var/conf/timelock.distributed.yml > var/conf/timelock.yml
                          && service/bin/init.sh console' ]
    ports:
      - "8421"
      - "8422"
    container_name: timelock2.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.6

  timelock3.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution:unspecified
    environment:
      HOSTNAME: timelock3.palantir.pt:8421
    command: [ bash, -c, 'sed "s/{{HOSTNAME}}/$${HOSTNAME}/g" var/conf/timelock.distributed.yml > var/conf/timelock.yml
                          && service/bin/init.sh console' ]
    ports:
      - "8421"
      - "8422"
    container_name: timelock3.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.7


  workload-server:
    image: palantirtechnologies/atlasdb-workload-server-distribution:unspecified
    command: [bash, -c, 'cp var/conf/workload-server.timelock.cassandra.yml var/conf/workload-server.yml
                         && dockerize -timeout 240s -wait tcp://cassandra11:9160 
                         -wait tcp://cassandra12:9160 -wait tcp://cassandra13:9160 
                         -wait tcp://cassandra14:9160 -wait tcp://cassandra15:9160 
                         -wait tcp://cassandra16:9160
                         && service/bin/init.sh console']
    ports:
      - "5005:5005" # enabling port for remote debugger
    container_name: workload-server
    depends_on:
      - cassandra11
      - cassandra12
      - cassandra13
      - cassandra14
      - cassandra15
      - cassandra16
      - cassandra21
      - cassandra22
      - cassandra23
      - cassandra24
      - cassandra25
      - cassandra26
      - timelock1.palantir.pt
      - timelock2.palantir.pt
      - timelock3.palantir.pt
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.8

networks:
  antithesis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24
